# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.0"
  title: NIDM API

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /projects:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Projects` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfProject
            type: array
            items:
              title: Project
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
  /projects/{projectId}:
    get:
      description: |
        Find project by projectId
      parameters:
        - 
          in: path
          name: projectId
          required: true
          type: integer
          format: int64
           
      responses:
        200:
          description: Succcesful
          